class_name NetworkLayer extends Node
##Base network layer class defining common interface

##Receive packet data FROM server
@warning_ignore("unused_signal")
signal data_received(packet_name: String, packet_data: Dictionary)

##Unique Player ID generated by server
var my_player_id: String

##Connect to server
func connect_to_server(_user_data: Dictionary) -> void:
	pass

##Send packet data TO server
func send_data(_packet_name: String, _packet_data: Dictionary) -> void:
	pass
